export interface ICustomerSurveyAttrs{
    id?: number,              
    officeId?: number,     
    firstName?: string,       
    lastName?: string,       
    fatherName?: string,
    motherName?: string,
    birthDate?: Date,
    mobileNumber?: string,
    religion?: number,
    gender?: number,
    maritialStatus?: number,      
    spouseName?: string,
    education?: number,
    occupation?: number,
    yearlyIncome?: number,
    familyMemberMale?: number,
    familyMemberFemale?: number,
    familyHead?: string,
    ownResidence?: string,
    residenceRemarks?: string,
    createdBy?: string,
    createdAt?: Date,
}